name: Simulated Jenkins Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build Application
        run: ./gradlew assemble

      - name: Run Tests
        run: ./gradlew test
